networks:
  #proxy-network:
  #  driver: bridge
  db-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.2.0/24
  cloudflare-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.1.0/24

services:
  mysql:
    container_name: mysql
    user: ${UID}:${GID}
    image: mysql:8.0.34
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      timeout: 20s
      retries: 10
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      db-network:
        ipv4_address: 172.17.2.1

  phpmyadmin:
    build:
      context: .
      dockerfile: dockerfile_pma
    container_name: phpmyadmin
    environment:
      TZ: ${TZ}
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 100M
    restart: always
    volumes:
      - ./_infra/phpmyadmin/config.secret.inc.php:/etc/phpmyadmin/config.secret.inc.php:ro
      - ./_infra/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      cloudflare-network:
        ipv4_address: 172.17.1.2
      db-network:
        ipv4_address: 172.17.2.2
  
  php-kumon:
    build:
      context: .
      dockerfile: dockerfile_php-kumon
    container_name: php-kumon
    user: ${UID}:${GID}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT: ${MYSQL_ROOT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_KUMON}
      MYSQL_USER: ${MYSQL_USER_KUMON}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_KUMON}
      ROOT_DIR: ${ROOT_DIR}
      KUMON_DIR: ${KUMON_DIR}
    volumes:
      - ./_infra/kumon/www/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
      - ./_infra/kumon/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./_infra/kumon/php/kumon.logrotate:/etc/logrotate.d/kumon
      - ./kumon/app:/var/www/html
      - ./_lib:/var/www/html/lib
      - ./nginx/certs:/var/www/cert
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      cloudflare-network:
        ipv4_address: 172.17.1.3
      db-network:
        ipv4_address: 172.17.2.3

  #nginx:
  #  image: nginx:latest
  #  container_name: nginx
  #  ports:
  #    - "443:443"
  #    - "80:80"
  #  volumes:
  #    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #    - ./nginx/certs:/etc/nginx/certs
  #    - ./nginx/vhost:/etc/nginx/conf.d
  #    - ./nginx/html:/usr/share/nginx/html
  #    - ./nginx/html_false:/etc/nginx/html
  #  restart: always
  #  depends_on:
  #    - php-kumon
  #  networks:
  #    - proxy-network
  #    - cloudflare-network

  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    volumes:
      - ./_infra/cloudflare:/etc/cloudflared
    networks:
      cloudflare-network:
        ipv4_address: 172.17.1.1
