version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
      - ./html:/etc/nginx/html
    restart: always
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
