tunnel: aba6ab0a-be50-4567-97ab-828974d386c1
credentials-file: /etc/cloudflared/cert.pem

ingress:
  - hostname: xmatrix.com.br
    service: https://nginx:443
    originRequest:
      noTLSVerify: true

  - hostname: pma.xmatrix.com.br
    service: https://phpmyadmin:443
    originRequest:
      noTLSVerify: true

  - hostname: kumon.xmatrix.com.br
    service: https://php-kumon:443
    originRequest:
      noTLSVerify: true

  - service: http_status:404
